import rawBooks from "./data/books.json";
import { coverWidthFor } from "./book-motion";

export type BookMotif =
  | "lattice"
  | "corrosion"
  | "efficiency"
  | "network"
  | "boom"
  | "organization"
  | "schematic"
  | "flight"
  | "circuit"
  | "orbit"
  | "branches"
  | "wave"
  | "runner"
  | "gather"
  | "maze"
  | "fracture"
  | "continuum"
  | "windows"
  | "steps";

/** One row of app/data/books.json, generated by scripts/build-catalog.mjs. */
export type Book = {
  id: string;
  title: string;
  shortTitle: string;
  author: string;
  series: string | null;
  isbn: string | null;
  isbn13: string | null;
  pages: number | null;
  format: string;
  avgRating: number | null;
  ratingsCount: number | null;
  /** ISO dates (YYYY-MM-DD). */
  published: string | null;
  originalPublished: string | null;
  myRating: number | null;
  timesRead: number;
  dateAdded: string | null;
  dateRead: string | null;
  recencyDate: string | null;
  url: string;
  motif: BookMotif;
  /** Scene units, like the reference catalog (≈1.7–2.2 tall). */
  height: number;
  thickness: number;
  /** Cover board width in scene units, derived from height. */
  width: number;
  coverImage?: string;
  cover: string;
  accent: string;
  ink: string;
};

type RawBook = Omit<Book, "width" | "motif"> & { motif: string };

/** Set at build time when the site is served from a sub-path (GitHub Pages). */
const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export const catalog: Book[] = (rawBooks as RawBook[]).map((book) => ({
  ...book,
  motif: book.motif as BookMotif,
  width: coverWidthFor(book.height),
  coverImage: book.coverImage ? `${basePath}${book.coverImage}` : undefined,
}));
